GET http://sendit11.herokuapp.com/api/v1/parcel/parcels
Content-Type: application/json

{
        "parcelName": "chickens",
        "destination": "lagos state, ikorodu, no 5 loau street",
        "pickupLocation": "ikorodu turning",
        "deliveredOn": "2018-11-18",
        "parcelStatus": "TRANSMITTING",
        "parcelWeight": "333",
        "placedBy": "20",
        "parcelWeightScale": "kg",
        "sentOn": "2018-11-18",
        "presentLocation": "isale oja, mowe, ajegunle"
}

