POST http://localhost:3040/api/v1/user/signup
Content-Type: application/json
Authorization: 
{
    "firstName": "alade",
    "lastName": "musa",
    "email": "aladeMusa@gmail.com",
    "password": "gggguuuu"
}

        "parcelName": "chickens",
        "destination": "lagos state, ikorodu, no 5 loau street",
        "pickupLocation": "ikorodu turning",
        "deliveredOn": "2018-11-18",
        "parcelStatus": "TRANSMITTING",
        "parcelWeight": "333",
        "placedBy": "20",
        "parcelWeightScale": "kg",
        "sentOn": "2018-11-18",
        "presentLocation": "isale oja, mowe, ajegunle"
