CREATE TABLE parcels(parcelId INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parcelName VARCHAR(100) NOT NULL, destination TEXT NOT NULL,
    pickupLocation VARCHAR(100) NOT NULL, deliveredOn DATE, presentLocation VARCHAR(100), parcelStatus TEXT,
    parcelWeight VARCHAR(100) NOT NULL, placedBy VARCHAR(100) NOT NULL, sentOn DATE,
    parcelWeightScale VARCHAR(100) NOT NULL);

INSERT INTO parcels(
    parcelName,
    destination,
    pickupLocation,
    presentLocation,
    deliveredOn,
    parcelStatus,
    parcelWeight,
    placedBy,
    sentOn,
    parcelWeightScale
  )
VALUES
  (
    'Television',
    'ajah, lagos',
    'songotedo',
    'lekki phase 1',
    '2018-11-18',
    'transittimg',
    '333',
    '20',
    '2018-11-18',
    '33kg'
  );

  CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  email VARCHAR(200) NOT NULL,
  password VARCHAR(100) NOT NULL,
  isAdmin BOOLEAN
);

INSERT INTO users (firstName, lastName, email, password, isAdmin)
VALUES
  (
    'orji',
    'Nna',
    'orji.Nna@gmail.com',
    'gggggguuuuuu',
     true
  );

